/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ApiTodosIdLazyImport = createFileRoute('/api/todos/$id')()
const ApiTodosLazyImport = createFileRoute('/api/todos')()

// Create/Update Routes

const ApiTodosIdLazyRoute = ApiTodosIdLazyImport.update({
  path: '/api/todos/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/api/todos/$id').then((d) => d.Route))

const ApiTodosLazyRoute = ApiTodosLazyImport.update({
  path: '/api/todos',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/api/todos').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/api/todos': {
      id: '/api/todos'
      path: '/api/todos'
      fullPath: '/api/todos'
      preLoaderRoute: typeof ApiTodosLazyImport
      parentRoute: typeof rootRoute
    }
    '/api/todos/$id': {
      id: '/api/todos/$id'
      path: '/api/todos/$id'
      fullPath: '/api/todos/$id'
      preLoaderRoute: typeof ApiTodosIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/todos': typeof ApiTodosLazyRoute
  '/api/todos/$id': typeof ApiTodosIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/todos': typeof ApiTodosLazyRoute
  '/api/todos/$id': typeof ApiTodosIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/api/todos': typeof ApiTodosLazyRoute
  '/api/todos/$id': typeof ApiTodosIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/todos' | '/api/todos/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/todos' | '/api/todos/$id'
  id: '__root__' | '/' | '/api/todos' | '/api/todos/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTodosLazyRoute: typeof ApiTodosLazyRoute
  ApiTodosIdLazyRoute: typeof ApiTodosIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTodosLazyRoute: ApiTodosLazyRoute,
  ApiTodosIdLazyRoute: ApiTodosIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/api/todos",
        "/api/todos/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/api/todos": {
      "filePath": "api/todos.ts"
    },
    "/api/todos/$id": {
      "filePath": "api/todos/$id.ts"
    }
  }
}
ROUTE_MANIFEST_END */
