/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContentTypeBuilderRouteImport } from './routes/content-type-builder'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserManagementIndexRouteImport } from './routes/user-management/index'
import { Route as MediaIndexRouteImport } from './routes/media/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ContentManagerIndexRouteImport } from './routes/content-manager/index'
import { Route as ApiDashboardIndexRouteImport } from './routes/api-dashboard/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentTypeBuilderRoute = ContentTypeBuilderRouteImport.update({
  id: '/content-type-builder',
  path: '/content-type-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementIndexRoute = UserManagementIndexRouteImport.update({
  id: '/user-management/',
  path: '/user-management/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentManagerIndexRoute = ContentManagerIndexRouteImport.update({
  id: '/content-manager/',
  path: '/content-manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardIndexRoute = ApiDashboardIndexRouteImport.update({
  id: '/api-dashboard/',
  path: '/api-dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/content-type-builder': typeof ContentTypeBuilderRoute
  '/login': typeof LoginRoute
  '/api-dashboard': typeof ApiDashboardIndexRoute
  '/content-manager': typeof ContentManagerIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/media': typeof MediaIndexRoute
  '/user-management': typeof UserManagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/content-type-builder': typeof ContentTypeBuilderRoute
  '/login': typeof LoginRoute
  '/api-dashboard': typeof ApiDashboardIndexRoute
  '/content-manager': typeof ContentManagerIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/media': typeof MediaIndexRoute
  '/user-management': typeof UserManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/content-type-builder': typeof ContentTypeBuilderRoute
  '/login': typeof LoginRoute
  '/api-dashboard/': typeof ApiDashboardIndexRoute
  '/content-manager/': typeof ContentManagerIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/media/': typeof MediaIndexRoute
  '/user-management/': typeof UserManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/content-type-builder'
    | '/login'
    | '/api-dashboard'
    | '/content-manager'
    | '/dashboard'
    | '/media'
    | '/user-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/content-type-builder'
    | '/login'
    | '/api-dashboard'
    | '/content-manager'
    | '/dashboard'
    | '/media'
    | '/user-management'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/content-type-builder'
    | '/login'
    | '/api-dashboard/'
    | '/content-manager/'
    | '/dashboard/'
    | '/media/'
    | '/user-management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContentTypeBuilderRoute: typeof ContentTypeBuilderRoute
  LoginRoute: typeof LoginRoute
  ApiDashboardIndexRoute: typeof ApiDashboardIndexRoute
  ContentManagerIndexRoute: typeof ContentManagerIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  MediaIndexRoute: typeof MediaIndexRoute
  UserManagementIndexRoute: typeof UserManagementIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-type-builder': {
      id: '/content-type-builder'
      path: '/content-type-builder'
      fullPath: '/content-type-builder'
      preLoaderRoute: typeof ContentTypeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management/': {
      id: '/user-management/'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof UserManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-manager/': {
      id: '/content-manager/'
      path: '/content-manager'
      fullPath: '/content-manager'
      preLoaderRoute: typeof ContentManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-dashboard/': {
      id: '/api-dashboard/'
      path: '/api-dashboard'
      fullPath: '/api-dashboard'
      preLoaderRoute: typeof ApiDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContentTypeBuilderRoute: ContentTypeBuilderRoute,
  LoginRoute: LoginRoute,
  ApiDashboardIndexRoute: ApiDashboardIndexRoute,
  ContentManagerIndexRoute: ContentManagerIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  MediaIndexRoute: MediaIndexRoute,
  UserManagementIndexRoute: UserManagementIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
